export const LANGUAGES = [
  { code: 'fa', label: 'فارسی' }, { code: 'en', label: 'English' }, { code: 'tr', label: 'Türkçe' },
  { code: 'ar', label: 'العربية' }, { code: 'de', label: 'Deutsch' },
]
export const DIGIT_STYLES = [
  { code: 'en', label: 'اعداد انگلیسی' }, { code: 'fa', label: 'اعداد فارسی' }, { code: 'ar', label: 'اعداد عربی' },
]
export const RTL_LANGUAGES = ['fa', 'ar']

const en = {
  'گزارش وضعیت':'Overview','هزینه‌ها':'Expenses','درآمدها':'Income','چک و بدهی':'Checks & debts','تنظیمات':'Settings',
  'افزودن':'Add','ویرایش':'Edit','حذف':'Delete','بستن':'Close','ذخیره':'Save','ذخیره اطلاعات':'Save details','انصراف':'Cancel','لغو':'Cancel','تأیید':'Confirm','بازگشت':'Undo','پرداخت شد':'Paid','دریافت شد':'Received','تسویه شد':'Settled','مشاهده جزئیات':'View details','تاریخچه':'History',
  'فعال':'Active','نزدیک سررسید':'Due soon','عقب‌افتاده':'Overdue','پرداخت شده':'Paid','پرداخت نشده':'Unpaid','دریافت شده':'Received','تسویه‌شده':'Settled','برگشت‌خورده':'Bounced','دریافت ناقص':'Partially received','دریافت نشده':'Not received','لغوشده':'Cancelled','آرشیو':'Archive',
  'زبان برنامه':'App language','نمایش اعداد':'Number display','واحد پول':'Currency','مخاطبین مالی':'Financial contacts','بانک‌ها':'Banks','دسته‌بندی‌ها':'Categories','تگ‌ها':'Tags','مدیریت بانک‌ها':'Manage banks','مدیریت دسته‌بندی‌ها':'Manage categories','مدیریت تگ‌ها':'Manage tags',
  'مجموع درآمد ماه جاری':'Current month income','درآمد دریافت‌شده':'Received income','درآمد مورد انتظار':'Expected income','مجموع هزینه ماه جاری':'Current month expenses','هزینه پرداخت‌شده':'Paid expenses','هزینه پرداخت‌نشده':'Unpaid expenses','بدهی‌های پرداختنی':'Payable debts','طلب‌های دریافتنی':'Receivables','جریان نقدی ماه جاری':'Current month cash flow','پیش‌بینی 30 روز آینده':'Next 30-day forecast',
  'عنوان':'Title','عنوان هزینه':'Expense title','عنوان درآمد':'Income title','مبلغ':'Amount','مبلغ کل':'Total amount','مبلغ دریافت‌شده':'Received amount','تاریخ شروع':'Start date','تاریخ پایان':'End date','تاریخ پایان، اختیاری':'End date, optional','تاریخ سررسید':'Due date','تاریخ سررسید / اولین پرداخت':'Due date / first payment','تاریخ دریافت / سررسید دریافت':'Receive / due date','توضیحات':'Description','دسته‌بندی':'Category','مخاطب مالی':'Financial contact','مخاطب مالی مرتبط':'Related contact','تگ‌ها':'Tags','نام فرد':'Person name','شماره حساب':'Account number','شماره کارت':'Card number','شماره شبا':'IBAN','کد ملی':'National ID','نام بانک':'Bank name','شماره چک':'Check number','وضعیت':'Status',
  'همه':'All','مرتب‌سازی:':'Sort:','بدون تاریخ':'No date','موردی برای نمایش وجود ندارد':'Nothing to display','از دکمه افزودن برای ثبت مورد جدید استفاده کنید.':'Use Add to create a new item.','اطلاعات پایه و مخاطبین مالی':'Base information and financial contacts','شخصی‌سازی و داده‌ها':'Preferences and data','واحد نمایش همه مبالغ برنامه':'Unit used for all amounts','زبان و جهت نمایش رابط کاربری':'Interface language and direction','شیوه نمایش ارقام در برنامه':'How digits are displayed','اعداد انگلیسی':'English digits','اعداد فارسی':'Persian digits','اعداد عربی':'Arabic digits',
  'پرداختنی':'Payable','دریافتنی':'Receivable','چک':'Check','بدهی':'Debt','سررسید':'Due','بدون دسته‌بندی':'Uncategorized','ثبت دریافت ناقص':'Record partial receipt','ثبت برگشت چک':'Mark check bounced','تکرارشونده بدون تاریخ پایان':'Repeats without end date','این مورد چک است':'This item is a check','تاریخ را به شکل شمسی وارد کنید.':'Enter the date in Jalali format.',
  'سلام، روز خوبی داشته باشید':'Hello, have a good day','وضعیت حساب‌های شما در یک نگاه':'Your financial status at a glance','خلاصه ماه جاری':'Current month summary','بر اساس اطلاعات ثبت‌شده':'Based on saved records','به‌روز':'Up to date','چک نزدیک سررسید':'Checks due soon','آیتم عقب‌افتاده':'Overdue items','درآمد منهای هزینه‌های این ماه':'Income minus this month expenses','برآورد جریان نقدی با توجه به سررسیدهای پیش رو':'Cash-flow estimate based on upcoming due dates',
}
const tr = {'گزارش وضعیت':'Genel Bakış','هزینه‌ها':'Giderler','درآمدها':'Gelirler','چک و بدهی':'Çekler ve borçlar','تنظیمات':'Ayarlar','افزودن':'Ekle','ویرایش':'Düzenle','حذف':'Sil','بستن':'Kapat','ذخیره':'Kaydet','ذخیره اطلاعات':'Bilgileri kaydet','انصراف':'İptal','لغو':'İptal','تأیید':'Onayla','بازگشت':'Geri al','پرداخت شد':'Ödendi','دریافت شد':'Alındı','تسویه شد':'Kapatıldı','فعال':'Aktif','نزدیک سررسید':'Vadesi yakın','عقب‌افتاده':'Gecikmiş','پرداخت شده':'Ödendi','پرداخت نشده':'Ödenmedi','دریافت شده':'Alındı','تسویه‌شده':'Kapatıldı','برگشت‌خورده':'Karşılıksız','دریافت ناقص':'Kısmen alındı','دریافت نشده':'Alınmadı','زبان برنامه':'Uygulama dili','نمایش اعداد':'Sayı gösterimi','واحد پول':'Para birimi','مخاطبین مالی':'Finansal kişiler','بانک‌ها':'Bankalar','دسته‌بندی‌ها':'Kategoriler','تگ‌ها':'Etiketler','مجموع درآمد ماه جاری':'Bu ay toplam gelir','درآمد دریافت‌شده':'Alınan gelir','درآمد مورد انتظار':'Beklenen gelir','مجموع هزینه ماه جاری':'Bu ay toplam gider','هزینه پرداخت‌شده':'Ödenen gider','هزینه پرداخت‌نشده':'Ödenmemiş gider','بدهی‌های پرداختنی':'Ödenecek borçlar','طلب‌های دریافتنی':'Alacaklar','جریان نقدی ماه جاری':'Bu ay nakit akışı','پیش‌بینی 30 روز آینده':'Gelecek 30 gün tahmini','عنوان':'Başlık','مبلغ':'Tutar','تاریخ شروع':'Başlangıç tarihi','تاریخ پایان':'Bitiş tarihi','تاریخ سررسید':'Vade tarihi','توضیحات':'Açıklama','دسته‌بندی':'Kategori','مخاطب مالی':'Finansal kişi','تگ‌ها':'Etiketler','نام فرد':'Kişi adı','شماره حساب':'Hesap numarası','شماره کارت':'Kart numarası','شماره شبا':'IBAN','کد ملی':'Kimlik numarası','نام بانک':'Banka adı','شماره چک':'Çek numarası','همه':'Tümü','مرتب‌سازی:':'Sırala:','موردی برای نمایش وجود ندارد':'Gösterilecek öğe yok','اعداد انگلیسی':'İngilizce rakamlar','اعداد فارسی':'Farsça rakamlar','اعداد عربی':'Arapça rakamlar'}
const ar = {'گزارش وضعیت':'نظرة عامة','هزینه‌ها':'المصروفات','درآمدها':'الإيرادات','چک و بدهی':'الشيكات والديون','تنظیمات':'الإعدادات','افزودن':'إضافة','ویرایش':'تعديل','حذف':'حذف','بستن':'إغلاق','ذخیره':'حفظ','ذخیره اطلاعات':'حفظ المعلومات','انصراف':'إلغاء','لغو':'إلغاء','تأیید':'تأكيد','بازگشت':'تراجع','پرداخت شد':'تم الدفع','دریافت شد':'تم الاستلام','تسویه شد':'تمت التسوية','فعال':'نشط','نزدیک سررسید':'قريب الاستحقاق','عقب‌افتاده':'متأخر','پرداخت شده':'مدفوع','پرداخت نشده':'غير مدفوع','دریافت شده':'مستلم','تسویه‌شده':'تمت التسوية','برگشت‌خورده':'مرتجع','دریافت ناقص':'استلام جزئي','دریافت نشده':'لم يستلم','زبان برنامه':'لغة التطبيق','نمایش اعداد':'عرض الأرقام','واحد پول':'العملة','مخاطبین مالی':'جهات الاتصال المالية','بانک‌ها':'البنوك','دسته‌بندی‌ها':'الفئات','تگ‌ها':'الوسوم','مجموع درآمد ماه جاری':'إجمالي دخل الشهر','درآمد دریافت‌شده':'الدخل المستلم','درآمد مورد انتظار':'الدخل المتوقع','مجموع هزینه ماه جاری':'إجمالي مصروفات الشهر','هزینه پرداخت‌شده':'المصروفات المدفوعة','هزینه پرداخت‌نشده':'المصروفات غير المدفوعة','بدهی‌های پرداختنی':'الديون المستحقة','طلب‌های دریافتنی':'المستحقات','جریان نقدی ماه جاری':'التدفق النقدي للشهر','پیش‌بینی 30 روز آینده':'توقعات 30 يوماً','عنوان':'العنوان','مبلغ':'المبلغ','تاریخ شروع':'تاريخ البدء','تاریخ پایان':'تاريخ الانتهاء','تاریخ سررسید':'تاريخ الاستحقاق','توضیحات':'الوصف','دسته‌بندی':'الفئة','مخاطب مالی':'جهة الاتصال المالية','تگ‌ها':'الوسوم','نام فرد':'اسم الشخص','شماره حساب':'رقم الحساب','شماره کارت':'رقم البطاقة','شماره شبا':'IBAN','کد ملی':'الرقم الوطني','نام بانک':'اسم البنك','شماره چک':'رقم الشيك','همه':'الكل','مرتب‌سازی:':'ترتيب:','موردی برای نمایش وجود ندارد':'لا توجد عناصر للعرض','اعداد انگلیسی':'أرقام إنجليزية','اعداد فارسی':'أرقام فارسية','اعداد عربی':'أرقام عربية'}
const de = {'گزارش وضعیت':'Übersicht','هزینه‌ها':'Ausgaben','درآمدها':'Einnahmen','چک و بدهی':'Schecks & Schulden','تنظیمات':'Einstellungen','افزودن':'Hinzufügen','ویرایش':'Bearbeiten','حذف':'Löschen','بستن':'Schließen','ذخیره':'Speichern','ذخیره اطلاعات':'Daten speichern','انصراف':'Abbrechen','لغو':'Abbrechen','تأیید':'Bestätigen','بازگشت':'Rückgängig','پرداخت شد':'Bezahlt','دریافت شد':'Erhalten','تسویه شد':'Beglichen','فعال':'Aktiv','نزدیک سررسید':'Bald fällig','عقب‌افتاده':'Überfällig','پرداخت شده':'Bezahlt','پرداخت نشده':'Unbezahlt','دریافت شده':'Erhalten','تسویه‌شده':'Beglichen','برگشت‌خورده':'Geplatzt','دریافت ناقص':'Teilweise erhalten','دریافت نشده':'Nicht erhalten','زبان برنامه':'App-Sprache','نمایش اعداد':'Zahlenanzeige','واحد پول':'Währung','مخاطبین مالی':'Finanzkontakte','بانک‌ها':'Banken','دسته‌بندی‌ها':'Kategorien','تگ‌ها':'Tags','مجموع درآمد ماه جاری':'Einnahmen des Monats','درآمد دریافت‌شده':'Erhaltene Einnahmen','درآمد مورد انتظار':'Erwartete Einnahmen','مجموع هزینه ماه جاری':'Ausgaben des Monats','هزینه پرداخت‌شده':'Bezahlte Ausgaben','هزینه پرداخت‌نشده':'Unbezahlte Ausgaben','بدهی‌های پرداختنی':'Zahlbare Schulden','طلب‌های دریافتنی':'Forderungen','جریان نقدی ماه جاری':'Cashflow des Monats','پیش‌بینی 30 روز آینده':'30-Tage-Prognose','عنوان':'Titel','مبلغ':'Betrag','تاریخ شروع':'Startdatum','تاریخ پایان':'Enddatum','تاریخ سررسید':'Fälligkeitsdatum','توضیحات':'Beschreibung','دسته‌بندی':'Kategorie','مخاطب مالی':'Finanzkontakt','تگ‌ها':'Tags','نام فرد':'Name','شماره حساب':'Kontonummer','شماره کارت':'Kartennummer','شماره شبا':'IBAN','کد ملی':'Nationale ID','نام بانک':'Bankname','شماره چک':'Schecknummer','همه':'Alle','مرتب‌سازی:':'Sortieren:','موردی برای نمایش وجود ندارد':'Keine Einträge vorhanden','اعداد انگلیسی':'Englische Ziffern','اعداد فارسی':'Persische Ziffern','اعداد عربی':'Arabische Ziffern'}

export const translations = { fa: {}, en, tr, ar, de }
